triangle_website/triangle_website/common/urls.py
from django.conf.urls import url
from triangle_website.common.views import *
from django.db import transaction

app_name = 'common'
urlpatterns = [
	url(r'^calendar/$', calendar, name='calendar'),
	url(r'^$', home_page, name='index'),
	url(r'^message/$', server_message, name='message'),
]

triangle_website/triangle_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^voting/', include('triangle_website.voting.urls')),
    url(r'^admin/', admin.site.urls),
	url('^auth/', include('triangle_website.auth.urls')),
	url(r'^', include('triangle_website.common.urls')),
]

triangle_website/triangle_website/voting/urls.py
from django.conf.urls import url
from .views import *

app_name = 'voting'
urlpatterns = [
	url(r'^$', voting_index, name='index'),
	url(r'^vote/(\d+)$', vote_page, name='vote'),
	url(r'^results/(\d+)$', results_page, name='results'),
	url(r'^new/$', new_vote, name='new'),
	url(r'^history/(\d+)$', history, name='history'),
	url(r'^create/$', create_vote, name='create'),
	url(r'^submit/(\d+)$', submit_vote, name='submit'),
	url(r'^search/$', search, name='search'),
	url(r'^vote/(\d+)/close/(True|False)/$', close_vote, name='close_vote')
]

triangle_website/triangle_website/common/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from urllib.parse import urlencode
from django.http import HttpResponse, HttpResponseRedirect

def calendar(request):
	return render(request, 'common/calendar.html')

def server_message(request):
	return render(request, 'common/server_message.html', context={'subject':request.GET['subject'], 'body':request.GET['body']})

def redir_to_mess(subject, body):
	return get_redirect('common:message', subject=subject, body=body)

# Url is the url to reverse. This adds the kwargs (which should be a dict) in the form of ?param1=val1
def get_redirect(url, **kwargs):
	url = reverse(url)
	params = urlencode(kwargs)
	return HttpResponseRedirect(url + '?' + params)

def home_page(request):
	return render(request, 'common/home.html')

triangle_website/triangle_website/common/templates/common/calendar.html
{% extends "common/header.html" %}
{% block title %}Utah Triangle Voting{% endblock %}
{% block content %}
{% include "common/navbar.html" with is_calendar=True %}
<div class="container theme-showcase" role="main">
	<iframe src="https://calendar.google.com/calendar/embed?src=dhddetccgao46pn45qt8gcna2g%40group.calendar.google.com&ctz=America/Denver" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->

triangle_website/triangle_website/common/templates/common/error.html
{% if error %}
  <div class="alert alert-danger" role="alert">
    <strong>Error:</strong> {{error}}
  </div>
{% endif %}

triangle_website/triangle_website/common/templates/common/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8"></meta>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
		<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content=""></meta>
		<meta name="author" content=""></meta>
		<link rel="icon" href="{% static 'common/images/favicon.ico' %}"></link>

		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap core CSS -->
		<link href="{% static 'common/bootstrap-3.3.6/css/bootstrap.min.css' %}" rel="stylesheet"></link>
		<!-- Bootstrap theme -->
		<link href="{% static 'common/bootstrap-3.3.6/css/bootstrap-theme.min.css' %}" rel="stylesheet"></link>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<link href="{% static 'common/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet"></link>

		<!-- Custom styles for this template -->
		<link href="{% static 'common/css/theme.css' %}" rel="stylesheet"></link>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	</head>
	<body role="document">

		{% block content %}{% endblock %}

		<!-- Bootstrap core JavaScript
		============================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		<script src="{% static 'common/bootstrap-3.3.6/js/bootstrap.min.js' %}"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<script src="{% static 'common/js/ie10-viewport-bug-workaround.js' %} "></script>
		{% block endscripts %}{% endblock %}
	</body>
</html>

triangle_website/triangle_website/common/templates/common/home.html
{% extends "common/header.html" %}
{% load staticfiles %}
{% block title %}Utah Triangle{% endblock %}
{% block content %}
<link href="{% static 'common/css/home.css' %}" rel="stylesheet">
{% include "common/navbar.html" with is_home=True %}
<div class="home_container">
	<!-- Carousel
	================================================== -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	  </ol>
	  <div class="carousel-inner" role="listbox">
		<div class="item active">
		  <img class="first-slide" src="{% static 'common/images/better_men.png' %}" alt="First slide">
		</div>
		<div class="item">
		  <img class="second-slide" src="{% static 'common/images/coat_of_arms_trans.png' %}" alt="Second slide">
		  <div class="container">
			<div class="carousel-caption">
			  <h1>A historied organization.</h1>
			  <p>Though Utah Triangle was chartered recently in Spring 2015, the national Triangle Fraternity was founded in 1907! Though many things have changed over the years, our organization continues to follow the same code of ethics as it has for over a century.</p>
			  <p><a class="btn btn-lg btn-primary" href="http://triangle.org/purpose/coe/" role="button">Learn more</a></p>
			</div>
		  </div>
		</div>
		<div class="item">
		  <img class="third-slide" src="{% static 'common/images/airbourne_spring2016.png' %}" alt="Third slide">
		  <div class="container">
			<div class="carousel-caption" style="color:#ffffff; text-shadow:none;">
			  <h1>Brothers for life.</h1>
			  <p>Contact us today to join the closest group of scientists, architects, and engineers at the University of Utah!</p>
			  <p><a class="btn btn-lg btn-primary" href="#" role="button">Contact us</a></p>
			</div>
		  </div>
		</div>
	  </div>
	  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	  </a>
	</div><!-- /.carousel -->
</div>
{% endblock %}

triangle_website/triangle_website/common/templates/common/navbar.html
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="{% url 'common:index' %}">Utah Triangle</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li {% if is_home %}class="active"{% endif %}><a href="{% url 'common:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
				<li {% if is_voting %}class="active"{% endif %}><a href="{% url 'voting:index' %}">Voting</a></li>
				{% if user.is_authenticated %}
				<li {% if is_calendar %}class="active"{% endif %}><a href="{% url 'common:calendar' %}">Calendar</a></li>
				<li {% if is_brothers_doc %}class="active"{% endif %}><a href="{% url 'brothers_doc' %}">Brothers</a></li>
				{% endif %}
				{% if user.is_staff %}
				<li><a href="{% url 'admin:index' %}">Admin</a></li>
				{% endif %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if not user.is_authenticated %}
				<li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
				<li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
				{% else %}
				<li><a href="{% url 'profile' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
				<li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>

triangle_website/triangle_website/common/templates/common/new_user.html
{% extends "common/header.html" %}
{% load staticfiles %}
{% block title %}Create New User{% endblock %}
{% block content %}
<link href="{% static 'voting/css/signin.css' %}" rel="stylesheet">
{% include "common/navbar.html" %}
<div class="container theme-showcase" role="main">
<script src='https://www.google.com/recaptcha/api.js'></script>
	{% if error %}
	<div class="alert alert-danger" role="alert">
		<strong>Error:</strong> {{error}}
	</div>
	{% endif %}
	
	<form class="form-signin" action="{% url 'common:create_user' %}" method="POST">
		{% csrf_token %}		
		<h2 class="form-signin-heading">Please sign up</h2>
		<label for="username" class="sr-only">Username</label>
		<input type="text" id="username" class="form-control" placeholder="Username" required autofocus name="user"></input>
		
		<label for="email" class="sr-only">Email</label>
		<input type="email" id="inputPasswordRep" class="form-control" placeholder="Email" required name="email"></input>
		
		<label for="firstname" class="sr-only">First name</label>
		<input type="text" id="firstname" class="form-control" placeholder="First name" required name="firstname"></input>
		
		<label for="lastname" class="sr-only">Last name</label>
		<input type="text" id="lastname" class="form-control" placeholder="Last name" required name="lastname"></input>
		
		<label for="inputPassword" class="sr-only">Password</label>
		<input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="pwd"></input>
		
		<label for="inputPassword" class="sr-only">Repeat password</label>
		<input type="password" id="inputPasswordRep" class="form-control" placeholder="Repeat password" required name="pwd_rep" style="margin-bottom:20px;"></input>
		
		<div class="g-recaptcha" data-sitekey="{{recaptcha_key}}"></div>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
	</form>
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->

triangle_website/triangle_website/common/templates/common/server_message.html
{% extends "common/header.html" %}
{% block title %}{{subject}}{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
<div class="container theme-showcase" role="main">
	<h1>{{subject}}</h1>
	<hr></hr>
	<p>{{body}}</p>
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->