triangle_website/triangle_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^voting/', include('triangle_website.voting.urls')),
    url(r'^admin/', admin.site.urls),
	url('^auth/', include('triangle_website.auth.urls')),
	url(r'^', include('triangle_website.common.urls')),
]

triangle_website/triangle_website/voting/urls.py
from django.conf.urls import url
from .views import *

app_name = 'voting'
urlpatterns = [
	url(r'^$', voting_index, name='index'),
	url(r'^vote/(\d+)$', vote_page, name='vote'),
	url(r'^results/(\d+)$', results_page, name='results'),
	url(r'^new/$', new_vote, name='new'),
	url(r'^history/(\d+)$', history, name='history'),
	url(r'^create/$', create_vote, name='create'),
	url(r'^submit/(\d+)$', submit_vote, name='submit'),
	url(r'^search/$', search, name='search'),
	url(r'^vote/(\d+)/close/(True|False)/$', close_vote, name='close_vote')
]

triangle_website/triangle_website/voting/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from collections import defaultdict
from django.contrib.auth import authenticate
import uuid
import collections
from contextlib import contextmanager
from django.db import reset_queries, connection

@contextmanager
def measure_queries():
    start = len(connection.queries)
    yield
    total = len(connection.queries) - start
    print(total)

# Not currently a full model with access to DB.
class Election(models.Model):
    # Uncomment the following line to force creation of votes to be tied to a user.
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    is_poll = models.BooleanField()
    is_open = models.BooleanField(default=True)

    def can_vote(self, user_ob):
        return len(Voter.objects.filter(user=user_ob).filter(election=self)) == 0

    # Returns either the passcode (which must be unique by db) or None if there is no passcode.
    def get_passcode(self):
        return Passcode.objects.filter(election=self).first()

    # Returns true if the passcode is valid or if there is no passcode.
    # This accepts a function so that getting a passcode is only invoked if
    # a passcode is actually needed.
    def check_passcode(self, get_passcode):
        code = self.get_passcode()
        return not (code != None and code.code != get_passcode())

    # Sets and returns the passcode.
    @transaction.atomic
    def set_passcode(self, passcode):
        result, was_created = Passcode.objects.get_or_create(election=self)
        result.code = passcode
        result.full_clean()
        result.save()
        return result

    # Sets that a particular user voted in this election. Returns None on failure.
    def set_voted(self, user):
        try:
            return Voter.objects.create(user=user, election=self)
        except:
            return None

    def __str__(self):
        return self.name

    def has_voted(self, user):
        return Voter.objects.filter(user=user).filter(election=self).exists()

    def can_see(self, user):
        if not (user.is_authenticated() or user.is_active):
            return False
        return self.get_passcode() is None or self.creator == user or self.has_voted(user)

    def get_all_voters(self):
        return Voter.objects.filter(election=self).order_by('user__first_name', 'user__last_name')

    # If current is true, then only open elections are returned.
    @staticmethod
    def get_all(user, current=False):
        if not (user.is_authenticated() or user.is_active):
            return set()
        valid_currency = lambda elec: elec.is_open or not current
        return {elec for elec in Election.objects.all() if elec.can_see(user) and valid_currency(elec)}

class Passcode(models.Model):
    code = models.CharField(max_length=255)
    election = models.OneToOneField(Election, on_delete=models.CASCADE, db_index=True)
    def __str__(self):
        return 'election:' + str(self.election) + ' code:' + str(self.code)

class Voter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    election = models.ForeignKey(Election, on_delete=models.CASCADE, db_index=True)

    class Meta:
        unique_together = ('user', 'election')

    def __str__(self):
        return 'user: ' + str(self.user) + ' election:' + str(self.election)

def get_vote_tabulator(question):
        # Get all vote choices -- necessary just in case no votes for candidate.
        choices = set(question.choice_set.all().select_related('question'))
        # Get all votes.
        votes_database = Vote.objects.all().filter(choice__question=question).select_related('choice').select_related('voter')
        votes = collections.defaultdict(set)
        for vote in votes_database:
            votes[vote.voter].add(vote)
        return VoteTabulator(choices, votes)

class VoteTabulator:
    def __init__(self, choices, votes):
        self.choices = choices
        self.votes = votes

    def exclude(self, excluded):
        for exclude in excluded:
            self.choices.discard(exclude)
            for voter, voter_votes in list(self.votes.items()):
                self.votes[voter] = {vote for vote in voter_votes if vote.choice not in excluded}

    def clone(self):
        choices = set(self.choices)
        votes = collections.defaultdict(set, ((voter, set(votes)) for voter, votes in self.votes.items()))
        return VoteTabulator(choices, votes)

    def compute_winner_count(self):
        vote_rank = lambda vote: vote.rank
        return collections.Counter(min(votes, key=vote_rank).choice for voter, votes in self.votes.items() if len(votes) > 0)

    def get_losers(self):
        vote_res = self.compute_winner_count()
        min_votes = min((vote_res[choice] for choice in self.choices), default=0)
        return [choice for choice in self.choices if vote_res[choice] == min_votes]

    def compute_winner(self):
        first_clone = self.clone()
        result = list()
        while len(first_clone.choices) > 0:
            second_clone = first_clone.clone()
            while len(second_clone.choices) > 0:
                losers = second_clone.get_losers()
                second_clone.exclude(losers)
            result.append(set(losers))
            first_clone.exclude(losers)
        return result

class Question(models.Model):
    name = models.CharField(max_length=255)
    election = models.ForeignKey(Election, on_delete=models.CASCADE, db_index=True)

    def votes(self):
        result = []
        for voter in self.election.anonvoter_set.all():
            result.append(voter.get_vote(self))
        return result

    def __str__(self):
        return self.name

    # This tabulates results for an alternative vote. Be sure to do a multithreaded test on this method.
    # The result is a list of sets in order of who has won, i.e., result[0] is the absolute winner, result[1] runner up, etc.
    # A winner set will always contain at least one member. If there is more than one member, that means that all members in the
    # winner set have tied.
    @transaction.atomic
    def get_results(self, exclusion=set()):
        # Check to see if done.
        if len(exclusion) == len(self.choice_set.all()):
            return []
        if self.election.is_poll:
            raise Exception('Can not get results for a poll from get_results.')

        result = get_vote_tabulator(self)
        result.exclude(exclusion)
        return result.compute_winner()

    def get_voters(self):
        return set(map(lambda vote: vote.voter, Vote.objects.filter(choice__question=self)))

class Choice(models.Model):
    text = models.CharField(max_length=255)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, db_index=True)

    # This is a convenience method for a poll to figure out how many voted for something.
    def sum_rank(self):
        # aggregate is kind of strange and returns a dictionary instead of the value itself.
        result = Vote.objects.filter(choice=self).aggregate(models.Sum('rank'))['rank__sum']
        if result:
            return result
        else:
            return 0

    def __str__(self):
        return self.text

# This is to collect votes for the Vote class. It stores a question mostly for convenience.
class AnonVoter(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE, db_index=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.responses = dict()

    # This gets the rank for this user for a particular choice. To get the rank, call result[choice.id].
    def get_vote(self, question_arg):
        result = dict()
        # Double underscore is to make python happy and is pretty much like choice.question.
        all_votes = Vote.objects.filter(choice__question=question_arg).filter(voter=self).select_related('choice')
        for vote in all_votes:
            result[vote.choice.id] = vote.rank
        return result

    # Returns the highest priority vote not in exclude. If all are excluded, then None is returned.
    @transaction.atomic
    def get_first_choice(self, question, exclude=set()):
        result = Vote.objects.filter(choice__question=question).filter(voter=self).order_by('rank')
        for vote in result:
            if vote.choice not in exclude:
                return vote.choice
        else:
            return None

    def __str__(self):
        return str(self.election)

class Vote(models.Model):
    # Can get back to question through the choice field.
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, db_index=True)
    rank = models.IntegerField()
    # This is anonymous and can not be traced back to a user.
    voter = models.ForeignKey(AnonVoter, on_delete=models.CASCADE)

    def __str__(self):
        return 'voter:' + str(self.voter) + ' choice:' + str(self.choice) + ' rank:' + str(self.rank)

class InvPasscode(Exception):
    def __init__(self, message='Error, invalid passcode.'):
        self.message = message

class VotingError(Exception):
    def __init__(self, message=''):
        self.message = message

triangle_website/triangle_website/voting/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.core.urlresolvers import reverse
import itertools
from django.db import transaction
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from triangle_website.common.views import redir_to_mess
from django.db import reset_queries, connection
import collections

def voting_index(request):
    get_votes = lambda current:sorted(list(Election.get_all(request.user, current=current)), key=lambda elec: -1 * elec.id)
    current_votes = get_votes(True)
    old_votes = get_votes(False)[:5]
    context = {"current_votes": current_votes, "complete_votes":old_votes, "error":request.GET.get('error')}
    return render(request, 'voting/index.html', context)

@login_required
@transaction.atomic
def vote_page(request, vote_id):
    vote = get_object_or_404(Election, pk=vote_id)
    if not vote.is_open:
        return HttpResponseRedirect(reverse('voting:results', args=[vote_id]))
    if vote.is_poll:
        temp = 'voting/vote_poll.html'
    else:
        temp = 'voting/vote.html'
    return render(request, temp, {"vote":vote})

@login_required
@transaction.atomic
def submit_vote(request, vote_id):
    try:
        # Should never fail except for very strange circumstances
        vote = Election.objects.get(pk=vote_id)

        if not vote.is_open:
            raise VotingError('Error, vote ' + vote_id + ' is not open at this time.')

        # Check passcode
        if not vote.check_passcode(lambda: request.POST['passcode']):
            raise InvPasscode()

        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        if not user or not user.is_active:
            raise VotingError('Error, incorrect username/password.')

        # Make sure you can't vote twice.
        if not vote.set_voted(user):
            raise VotingError('Error, ' + user.username + ' has already voted in ' + vote.name)

        save_vote(request, vote)
        return HttpResponseRedirect(reverse('voting:results', args=[str(vote.id)]))
    except Exception as e:
        return redir_to_mess('Voting Error', e.message)


# This is just a helper method, not an actual view.
@transaction.atomic
def save_vote(request, elec):
    voter = AnonVoter(election=elec)
    voter.save()

    if (elec.is_poll):
        for question in elec.question_set.all():
            id = str(question.id)
            if id in request.POST:
                selected = int(request.POST[str(question.id)])
                new_vote = Vote(choice=Choice.objects.get(pk=selected), rank=1, voter=voter)
                new_vote.save()
    else: # Vote is alternative vote.
        for question in elec.question_set.all():
            for choice in question.choice_set.all():
                opt = str(question.id) + ':' + str(choice.id)
                if opt in request.POST:
                    # TODO Verify vote data.
                    new_vote = Vote(rank=int(request.POST[opt]), choice=choice, voter=voter)
                    new_vote.save()

@login_required
def results_page(request, vote_id):
    vote = get_object_or_404(Election, pk=vote_id)
    can_close = vote.creator == request.user
    context = {'election':vote, 'can_close':can_close}
    if vote.is_poll:
        temp = 'voting/results_poll.html'
    else:
        temp = 'voting/results.html'
        context['winner_strs'] = {question : get_winner_str(question) for question in vote.question_set.all()}
    result = render(request, temp, context)
    return result

# Constructs a string of the form one; tie second, third
def get_winner_str(question):
    winner_str = ''
    first1 = True
    for winner_set in question.get_results():
        if first1:
            first1 = False
        else:
            winner_str += '; '
        first2 = True
        for winner in winner_set:
            if first2:
                if len(winner_set) > 1:
                    winner_str += 'tie '
                winner_str += winner.text
                first2 = False
            else:
                winner_str += ', ' + winner.text
    return winner_str

@login_required
def new_vote(request):
    #return get_redirect('voting:message', subject='Hello', body='World')
    return render(request, 'voting/new_vote.html')

def history(request, page):
    elections = Election.get_all(request.user)
    return render(request, 'voting/history.html', context={'elections':elections})

# A helper method for managing things. ** CAUTION: Deletes all elections **
def delete_votes():
    for elec in Election.objects.all():
        elec.delete()

@login_required
@transaction.atomic
def create_vote(request):
    new_vote = Election()
    new_vote.is_poll = request.POST["voteType"] == "poll"
    new_vote.name = request.POST["voteName"]
    new_vote.creator = request.user
    new_vote.save()
    if 'useCode' in request.POST:
        new_vote.set_passcode(request.POST['passcode'])

    # Keep iterating until a question/choice combo isn't found.
    for quesCount in itertools.count(1):
        quesId = 'q' + str(quesCount)
        if quesId in request.POST:
            new_ques = Question(name=request.POST[quesId], election=new_vote)
            new_ques.save()
            for choiceCount in itertools.count(1):
                choiceId = quesId + 'c' + str(choiceCount)
                if choiceId in request.POST:
                    newChoice = Choice(text=request.POST[choiceId], question=new_ques)
                    newChoice.save()
                else:
                    break
        else:
            break
    return HttpResponseRedirect(reverse('voting:index'))

@login_required
def search(request):
    vote_id = request.POST['vote_id']
    if not vote_id.isdigit():
        return get_redirect('voting:index', error='Invalid vote id ' + vote_id)
    vote = get_object_or_404(Election, pk=vote_id)
    if not vote.check_passcode(lambda:request.POST.get('passcode')):
        return get_redirect('voting:index', error='Invalid passcode for vote ' + vote_id + '.')
    return HttpResponseRedirect(reverse('voting:vote', args=[vote_id]))

@login_required
@transaction.atomic
def close_vote(request, vote_id, close_vote):
    close_vote = close_vote == 'True'
    vote = get_object_or_404(Election, pk=vote_id)
    if request.user == vote.creator:
        vote.is_open= not close_vote
        vote.save()
        return redir_to_mess('Vote ' + str(vote.id) + ' Closed' if close_vote else ' Opened', 'Succesfully ' + ('closed ' if close_vote else 'opened ') + vote.name)
    else:
        return redir_to_mess('Permissions Error', 'Could not close ' + vote.name + ' because you are not the creator of that vote.')

triangle_website/triangle_website/voting/templates/voting/close_vote.html
{% if can_close %}
<div class="row">
	{% if election.is_open %}
	<a href="{% url 'voting:close_vote' election.id 'True' %}" class="btn btn-primary">Close vote</a>
	{% else %}
	<a href="{% url 'voting:close_vote' election.id 'False' %}" class="btn btn-primary">Re-open vote</a>
	{% endif %}
</div>
{% endif %}

triangle_website/triangle_website/voting/templates/voting/history.html
{% extends "common/header.html" %}
{% block title %}Utah Triangle Voting{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
<div class="container theme-showcase" role="main">
	<h1>History of All Votes</h1>
	{% for elec in elections %}
	<ul class="list-group">
		<a href="{% url 'voting:results' elec.id %}" class="list-group-item">
			<h4 class="list-group-item-heading">Vote #{{elec.id}}</h4>
			<p class="list-group-item-text">{{elec.name}}</p>
		</a>
	</ul>
	{% endfor %}
	</div>
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->

triangle_website/triangle_website/voting/templates/voting/index.html
{% extends "common/header.html" %}
{% block title %}Utah Triangle Voting{% endblock %}
{% block content %}
{% include "common/navbar.html" with is_voting=True %}
<div class="container theme-showcase" role="main">
	{% if error %}
	<div class="alert alert-danger" role="alert">
		<strong>Error:</strong> {{error}}
	</div>
	{% endif %}

	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Voting for Utah Triangle</h1>
		<p>Examine the various votes available as well as the results of completed elections. If a vote isn't visible, ensure that you have the correct permissions to see the vote or search for the vote using the vote's ID.{% if user.is_authenticated and user.is_active %}<a class="btn btn-primary btn-lg" href="{% url 'voting:new' %}" role="button">Create New Vote <span class="glyphicon glyphicon-plus"></span></a>{% else %} Sign up today to create new votes.{% endif %}</p>
	</div>
	
	{% if user.is_authenticated and user.is_active %}
	<hr></hr>
	<h3>Search for votes</h3>
	
	<!--Do a POST for security since POST parameters are encrypted with https but not GET parameters-->
	<form role="form" action="{% url 'voting:search' %}" method="POST">
		{% csrf_token %}
		<div class="form-group">
			<label for="vote_id">Vote ID</label>
			<input type="text" class="form-control" id="vote_id" placeholder="Enter vote ID" name="vote_id"></input>
		</div>
		<div class="form-group">
			<label for="passcode">Passcode (if required)</label>
			<input type="text" class="form-control" id="passcode" placeholder="Enter passcode if vote uses passcode" name="passcode"></input>
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Search</button>
		</div>
	</form>
	
	<hr></hr>

	<div class="row">
		<div class="col-sm-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Current Votes</h3>
				</div>
				<div class="panel-body">
					<ul class="list-group">
						{% for vote in current_votes %}
						<a href="{% url 'voting:vote' vote.id %}" class="list-group-item">
							<h4 class="list-group-item-heading">Vote #{{vote.id}}</h4>
							<p class="list-group-item-text">{{vote.name}}</p>
						</a>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Completed Votes <button type="button" class="btn btn-info btn-xs" onclick="window.location='{% url 'voting:history' 1 %}'; return false;"><span class="glyphicon glyphicon-stats"></span> Full History</button></h3>
				</div>
				<div class="panel-body">
					<ul class="list-group">
						{% for vote in complete_votes %}
						<a href="{% url 'voting:results' vote.id %}" class="list-group-item">
							<h4 class="list-group-item-heading">Vote #{{vote.id}}</h4>
							<p class="list-group-item-text">{{vote.name}}</p>
						</a>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
	{% endif %}
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->

triangle_website/triangle_website/voting/templates/voting/new_vote.html
{% extends "common/header.html" %}
{% load staticfiles %}
{% block title %}Vote #1234{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
<link rel="stylesheet" href="{% static 'voting/css/form.css' %}"></link>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular.min.js"></script>
<div class="container theme-showcase" role="main" ng-app="formApp" ng-controller="mainControl">
	<div>
		<form class="form-horizontal" role="form" action="{% url "voting:create" %}" method="post">
		{% csrf_token %}
			<div class="form-group">
				<label class="control-label col-sm-2 title-input" for="voteName">Vote name:</label>
				<div class="col-sm-8">
					<input type="text" class="form-control input-lg" id="vote_name" placeholder="Enter name of vote" name="voteName"></input>
				</div>
				<div class="col-sm-2">
					<button type="button" class="btn btn-default btn-circle btn-lg" ng-click="questions.push(getQuestion())">
						<span class="glyphicon glyphicon-plus"></span>
					</button>
					<button type="button" class="btn btn-default btn-circle btn-lg" ng-click="questions.pop()">
						<span class="glyphicon glyphicon-minus"></span>
					</button>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2" for="pwd">Vote type:</label>
				<div class="col-sm-10"> 
					<label class="radio-inline"><input type="radio" name="voteType" checked value="poll">Poll</input></label>
					<label class="radio-inline"><input type="radio" name="voteType" value="altVote">Alternative vote</input></label>
				</div>
			</div>
			<div class="form-group">
				<div class="checkbox col-sm-offset-2 col-sm-10">
					<label><input type="checkbox" name="useCode" value="useCode" ng-model="useCode">Lock voting to passcode:</input></label>
				</div>
			</div>
			<div class="form-group" ng-show="useCode">
				<label class="control-label col-sm-2">Voting passcode:</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="vote_name" placeholder="Enter name of vote" name="passcode"></input>
				</div>
			</div>
			
			{% verbatim %}
			<span ng-repeat="question in questions track by $index">
				<hr></hr>
				<div class="form-group">
					<label class="control-label col-sm-2">Question {{$index + 1}}:</label>
					<div class="col-sm-8">
						<input type="text" class="form-control" id="text" placeholder="Enter a question" name="q{{$index+1}}"></input>
					</div>
					<div class="col-sm-2">
						<button type="button" class="btn btn-default btn-circle" ng-click="question.choices.push('')">
							<span class="glyphicon glyphicon-plus"></span>
						</button>
						<button type="button" class="btn btn-default btn-circle" ng-click="question.choices.pop()">
							<span class="glyphicon glyphicon-minus"></span>
						</button>
					</div>
				</div>
				<div class="form-group" ng-repeat="option in question.choices track by $index">
					<label class="control-label col-sm-2 input-sm">Option {{$index + 1}}:</label>
					<div class="col-sm-8">
						<input type="text" class="form-control input-sm" id="text" placeholder="Enter an option" name="q{{$parent.$index + 1}}c{{$index + 1}}"></input>
					</div>
				</div>
			</span>
			{% endverbatim %}
			
			<div class="form-group"> 
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Create</button>
				</div>
			</div>
		</form>
	</div>
</div> <!-- /container -->
<script src="{% static 'voting/js/new_vote.js' %}"></script>
{% endblock %} <!--{1}** Ending the content block **{1}>

triangle_website/triangle_website/voting/templates/voting/results_base.html
{% extends "common/header.html" %}
{% block title %}Votes #{{election.id}} Results{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
{% load voting_tags %}
<div class="container theme-showcase" role="main">
	
	<h1>{{election.name}} Results: {% if election.is_open %}<a href="{% url 'voting:vote' election.id %}">vote again</a>{% endif %}</h1>
	
	{% if not election.is_open %}
		{% block vote_results %}
		{% endblock %}
	{% endif %}
	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Voters in this election</h3>
			</div>
			<ul class="list-group">
			{% for voter in election.get_all_voters %}
				<li class="list-group-item">{{voter.user.username}}:{{voter.user.first_name}} {{voter.user.last_name}}</li>
			{% endfor %}
			</ul>
		</div>
	</div>
	
	{% if can_close %}
		<div class="row">
			{% if election.is_open %}
			<a href="{% url 'voting:close_vote' election.id 'True' %}" class="btn btn-primary">Close vote</a>
			{% else %}
			<a href="{% url 'voting:close_vote' election.id 'False' %}" class="btn btn-primary">Re-open vote</a>
			{% endif %}
		</div>
	{% endif %}
	
</div> <!-- /container -->
{% endblock %} <!-- Ending the content block -->

triangle_website/triangle_website/voting/templates/voting/vote.html
{% extends "common/header.html" %}
{% block title %}Vote #{{vote.id}}{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
<div class="container theme-showcase" role="main">
	<div class="page-header">
		<h1>{{vote.name}} - <a href="{% url 'voting:results' vote.id %}">see results</a></h1>
	</div>
	
	<div>
		<form class="form-horizontal" role="form" action="{% url "voting:submit" vote.id %}" method="post">
			{% include 'voting/voter_header.html' %}
			
			{% for question in vote.question_set.all %}
			<hr></hr>
			<h3>{{question.name}}</h3>
			<hr></hr>
			
			{% for choice in question.choice_set.all %}
			<div class="form-group">
				<label class="control-label col-sm-2" for="email">{{choice.text}}:</label>
				<div class="col-sm-10">
					{% for _ in question.choice_set.all %}
					<label class="radio-inline"><input type="radio" name="{{question.id}}:{{choice.id}}" value="{{forloop.counter}}">{{forloop.counter}}</input></label>
					{% endfor %}
				</div>
			</div>
			{% endfor %}
			{% endfor %}
			
			<div class="form-group"> 
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Submit</button>
				</div>
			</div>
		</form>
	</div>
</div> <!-- /container -->
{% endblock %} <!--{1}** Ending the content block **{1}>
	

triangle_website/triangle_website/voting/templates/voting/vote_poll.html
{% extends "common/header.html" %}
{% load staticfiles %}
{% block title %}Vote #{{vote.id}}{% endblock %}
{% block content %}
{% include "common/navbar.html" %}
<link rel="stylesheet" href="{% static 'voting/css/form.css' %}"></link>
<div class="container theme-showcase" role="main">
	<div class="page-header">
		<h1>{{vote.name}} - <a href="{% url 'voting:results' vote.id %}">see results</a></h1>
	</div>
	
	<div>
		<form class="form-horizontal" role="form" action="{% url "voting:submit" vote.id %}" method="post">
			{% include 'voting/voter_header.html' %}
			
			{% for question in vote.question_set.all %}
			<hr></hr>
			<h3>{{question.name}}</h3>
			<hr></hr>
			
			<div class="form-group">
				{% for choice in question.choice_set.all %}
				<div class="radio col-sm-offset-2 col-sm-10">
					<label><input type="radio" name="{{question.id}}" value="{{choice.id}}">{{choice.text}}</input></label>
				</div>
				{% endfor %}
			</div>
			{% endfor %}
			
			<div class="form-group"> 
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Submit</button>
				</div>
			</div>
		</form>
	</div>
</div> <!-- /container -->
{% endblock %} <!--{1}** Ending the content block **{1}>
	

triangle_website/triangle_website/voting/templates/voting/who_voted.html
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Voters in this election</h3>
		</div>
		<ul class="list-group">
		{% for voter in election.get_all_voters %}
			<li class="list-group-item">{{voter.user.username}}:{{voter.user.first_name}} {{voter.user.last_name}}</li>
		{% endfor %}
		</ul>
	</div>
</div>